--- 
- 
  become: true
  become_method: sudo
  become_user: root
  hosts: servers
  name: "perform yum update / reboot server"
  remote_user: root
  tasks: 
    - 
      name: "Perform yum update of all packages"
      yum: 
        name: "*"
        state: latest
#    - 
#     name: Download prometheus 
#      get_url:
#        url: https://github.com/prometheus/prometheus/releases/download/v2.18.1/prometheus-2.18.1.linux-amd64.tar.gz
#        dest: /root
#    - 
#      unarchive:
#        src: https://github.com/prometheus/prometheus/releases/download/v2.18.1/prometheus-2.18.1.linux-amd64.tar.gz
#        dest: /root
#        remote_src: yes
    - 
      file:
        path: /etc/yum.repos.d/grafana.repo
        state: touch
        owner: root
    - 
      blockinfile:
        path: /etc/yum.repos.d/grafana.repo
        block: |
          [grafana]
          name=grafana
          baseurl=https://packages.grafana.com/oss/rpm
          repo_gpgcheck=1
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.grafana.com/gpg.key
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    - 
      yum:
        name: grafana
        state: latest
    - 
      systemd:
        state: started
        name: grafana-server
        enabled: yes
 

